<a href="https://colab.research.google.com/github/Geethika1205/SML/blob/main/Loan%20approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/loan_data.csv")

In [5]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [22]:
df['person_gender']=df['person_gender'].replace({'male':0,'female':1})
df['person_education']=df['person_education'].replace({'High School':0,'Bachelor':1,'Master':2,'University':3,'Associate':4})
df['person_home_ownership']=df['person_home_ownership'].replace({'RENT':0,'OWN':1,'MORTGAGE':2})
df['loan_intent']=df['loan_intent'].replace({'PERSONAL':0,'EDUCATION':1,'MEDICAL':2,'HOMEIMPROVEMENT':3,'DEBTCONSOLIDATION':4,})
df['previous_loan_defaults_on_file']=df['previous_loan_defaults_on_file'].replace({'No':0,'Yes':1})

In [23]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,1,2,71948.0,0,0,35000.0,0,16.02,0.49,3.0,561,0,1
1,21.0,1,0,12282.0,0,1,1000.0,1,11.14,0.08,2.0,504,1,0
2,25.0,1,0,12438.0,3,2,5500.0,2,12.87,0.44,3.0,635,0,1
3,23.0,1,1,79753.0,0,0,35000.0,2,15.23,0.44,2.0,675,0,1
4,24.0,0,2,66135.0,1,0,35000.0,2,14.27,0.53,4.0,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,0,4,47971.0,6,0,15000.0,2,15.66,0.31,3.0,645,0,1
44996,37.0,1,4,65800.0,17,0,9000.0,3,14.07,0.14,11.0,621,0,1
44997,33.0,0,4,56942.0,7,0,2771.0,4,10.02,0.05,10.0,668,0,1
44998,29.0,0,1,33164.0,4,0,12000.0,1,13.23,0.36,6.0,604,0,1
44999,24.0,0,0,51609.0,1,0,6665.0,4,17.05,0.13,3.0,628,0,1